In [69]:
from google.colab import drive
drive.mount("/content/drive/")


Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving heart_rate_non_linear_features_train.csv to heart_rate_non_linear_features_train.csv


In [ ]:
#Store the data into a variable
df = pd.read_csv('heart_rate_non_linear_features_train.csv')
#Print the first 7 rows of the data
df. head(7)

uuid        SD1  ...  datasetId     condition
0  89df2855-56eb-4706-a23b-b39363dd605a  11.001565  ...          2     no stress
1  80c795e4-aa56-4cc0-939c-19634b89cbb2   9.170129  ...          2  interruption
2  c2d5d102-967c-487d-88f2-8b005a449f3e  11.533417  ...          2  interruption
3  37eabc44-1349-4040-8896-0d113ad4811f  11.119476  ...          2     no stress
4  aa777a6a-7aa3-4f6e-aced-70f8691dd2b7  13.590641  ...          2     no stress
5  fe7b4ab0-42d3-48d0-8479-7b022d6af0bc   7.026695  ...          2     no stress
6  d324b1ee-aaa1-4edb-9b46-c597cb0bbd8c   7.528700  ...          2     no stress

[7 rows x 7 columns]

In [83]:
df.shape

(369289, 7)

In [84]:
df.head()


uuid        SD1  ...  datasetId     condition
0  89df2855-56eb-4706-a23b-b39363dd605a  11.001565  ...          2     no stress
1  80c795e4-aa56-4cc0-939c-19634b89cbb2   9.170129  ...          2  interruption
2  c2d5d102-967c-487d-88f2-8b005a449f3e  11.533417  ...          2  interruption
3  37eabc44-1349-4040-8896-0d113ad4811f  11.119476  ...          2     no stress
4  aa777a6a-7aa3-4f6e-aced-70f8691dd2b7  13.590641  ...          2     no stress

[5 rows x 7 columns]

In [ ]:
x = df.iloc[:, :-1].values 

y = df.iloc[:, -1].values

In [ ]:
print(x)

[['89df2855-56eb-4706-a23b-b39363dd605a' 11.00156458989638
  199.06178216717808 2.139754004084331 1.16348520443103 2]
 ['80c795e4-aa56-4cc0-939c-19634b89cbb2' 9.170129223465477
  114.63445846671009 2.17449878482957 1.084710589600687 2]
 ['c2d5d102-967c-487d-88f2-8b005a449f3e' 11.53341727967178
  118.9392534780744 2.1353497073074 1.176314829766625 2]
 ...
 ['fd717478-95c3-48fc-bcdc-3adebae824ab' 16.30453006084595
  133.79779277497758 2.215642653225984 1.140232160841966 2]
 ['a0fc861e-3254-4210-bd5d-37870245f7da' 11.83855288886347
  110.3114741435717 2.091628465684143 1.1819371756037609 2]
 ['1f2eb52d-4f09-4921-a383-ef1bc6221789' 14.606306528298768
  94.6178007824552 2.20819311818382 1.234086863197041 2]]


In [ ]:
print(y)

['no stress' 'interruption' 'interruption' ... 'no stress' 'no stress'
 'no stress']


In [ ]:
from sklearn.impute import SimpleImputer
# To replace the missing value we create below object of SimpleImputer class
imputa = SimpleImputer(missing_values = np.nan, strategy = 'mean')
''' Using the fit method, we apply the imputa object on the matrix of our feature x.
The fit() method identifies the missing values and computes the mean of such feature a missing value is present.
'''
imputa.fit(x[:, 1:3])
# Repalcing the missing value using transform method
x[:, 1:3] = imputa.transform(x[:, 1:3])

In [ ]:
print(x)

[['89df2855-56eb-4706-a23b-b39363dd605a' 11.00156458989638
  199.06178216717808 2.139754004084331 1.16348520443103 2]
 ['80c795e4-aa56-4cc0-939c-19634b89cbb2' 9.170129223465477
  114.63445846671009 2.17449878482957 1.084710589600687 2]
 ['c2d5d102-967c-487d-88f2-8b005a449f3e' 11.53341727967178
  118.9392534780744 2.1353497073074 1.176314829766625 2]
 ...
 ['fd717478-95c3-48fc-bcdc-3adebae824ab' 16.30453006084595
  133.79779277497758 2.215642653225984 1.140232160841966 2]
 ['a0fc861e-3254-4210-bd5d-37870245f7da' 11.83855288886347
  110.3114741435717 2.091628465684143 1.1819371756037609 2]
 ['1f2eb52d-4f09-4921-a383-ef1bc6221789' 14.606306528298768
  94.6178007824552 2.20819311818382 1.234086863197041 2]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder= 'passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

  (0, 198548)	1.0
  (0, 369289)	11.00156458989638
  (0, 369290)	199.06178216717808
  (0, 369291)	2.139754004084331
  (0, 369292)	1.16348520443103
  (0, 369293)	2.0
  (1, 185448)	1.0
  (1, 369289)	9.170129223465477
  (1, 369290)	114.63445846671009
  (1, 369291)	2.17449878482957
  (1, 369292)	1.084710589600687
  (1, 369293)	2.0
  (2, 280786)	1.0
  (2, 369289)	11.53341727967178
  (2, 369290)	118.9392534780744
  (2, 369291)	2.1353497073074
  (2, 369292)	1.176314829766625
  (2, 369293)	2.0
  (3, 80355)	1.0
  (3, 369289)	11.11947630809331
  (3, 369290)	127.3185974177068
  (3, 369291)	2.178340631129962
  (3, 369292)	1.1796881390164051
  (3, 369293)	2.0
  (4, 245440)	1.0
  :	:
  (369284, 369293)	2.0
  (369285, 5822)	1.0
  (369285, 369289)	9.734242696210528
  (369285, 369290)	105.5025477856963
  (369285, 369291)	2.131264452080069
  (369285, 369292)	1.175975350580552
  (369285, 369293)	2.0
  (369286, 365583)	1.0
  (369286, 369289)	16.30453006084595
  (369286, 369290)	133.79779277497758
  (369286

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 0 ... 1 1 1]


In [77]:
from sklearn.model_selection import train_test_split


In [81]:
df.describe()

SD1            SD2         sampen         higuci  datasetId
count  369289.000000  369289.000000  369289.000000  369289.000000   369289.0
mean       10.593708     154.178997       2.062471       1.182292        2.0
std         2.914795     109.170222       0.206999       0.062192        0.0
min         3.911344      38.307745       0.434576       1.033984        2.0
25%         8.368340      90.326864       2.032977       1.139929        2.0
50%        10.196621     116.221063       2.134214       1.174293        2.0
75%        12.679005     166.764850       2.181929       1.223621        2.0
max        18.836107     796.852945       2.234841       1.361219        2.0

In [85]:
df.isnull()

uuid    SD1    SD2  sampen  higuci  datasetId  condition
0       False  False  False   False   False      False      False
1       False  False  False   False   False      False      False
2       False  False  False   False   False      False      False
3       False  False  False   False   False      False      False
4       False  False  False   False   False      False      False
...       ...    ...    ...     ...     ...        ...        ...
369284  False  False  False   False   False      False      False
369285  False  False  False   False   False      False      False
369286  False  False  False   False   False      False      False
369287  False  False  False   False   False      False      False
369288  False  False  False   False   False      False      False

[369289 rows x 7 columns]

In [86]:
df.isnull().sum()

uuid         0
SD1          0
SD2          0
sampen       0
higuci       0
datasetId    0
condition    0
dtype: int64

In [101]:
import numpy as np
from sklearn.model_selection import train_test_split

In [110]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]
 
# split the dataset
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.02, random_state=1)


In [114]:
print(x_train)


                                        uuid        SD1  ...    higuci  datasetId
250453  4e215248-1cf5-453f-b6d9-9ce48baa8dff   8.454017  ...  1.097470          2
131662  cd6e7270-f712-44e0-8001-c69cc9e5c323  14.633762  ...  1.171693          2
49100   e442ebfe-7b28-4aa8-abd0-cbe44c80035a  11.423894  ...  1.104628          2
10702   464c0759-b56a-450c-945a-ebd4d5505bce   8.431194  ...  1.082924          2
121797  b12fdc9d-c59a-4105-b206-3749df681885   7.501968  ...  1.069070          2
...                                      ...        ...  ...       ...        ...
117583  487535e7-7f47-408f-adb1-c7022cfa5390   6.926046  ...  1.141405          2
73349   197d31ac-b1f1-4440-93ef-efeedddee341  18.457618  ...  1.241837          2
312201  5fe63eab-9653-4e0e-9cad-c64cde8bd6e4   6.738828  ...  1.178160          2
267336  b06e8342-b4cd-4c54-8393-f9d282126a7e  11.328886  ...  1.183054          2
128037  d1ed9d3c-7455-43a7-b0dd-d4aed8804584   6.357843  ...  1.166421          2

[361903 rows x 

In [115]:
print(x_test)

                                        uuid        SD1  ...    higuci  datasetId
47340   80ffbdb6-9cee-44b7-91b3-cf26ac25e5d5  10.235520  ...  1.162558          2
93858   eb61e4c8-c28f-4087-82b8-b427a5a52bef   7.750247  ...  1.157278          2
201163  80f5f9e2-a85d-4a51-8b89-39505b206ccf   8.678615  ...  1.184945          2
364634  c81a3c50-ee66-459a-9d55-a8261093c724  11.998805  ...  1.147558          2
54177   21eef6fc-3b7d-4ec7-a07e-202ca0075a4d  13.939728  ...  1.321684          2
...                                      ...        ...  ...       ...        ...
260442  d3e71cd1-5ed4-408d-9e06-72e013dc30bb   9.994420  ...  1.181154          2
254967  60491e54-94c5-4dce-ab6e-c3021db5b833   7.011343  ...  1.150296          2
311243  ae461c66-ec6c-4cfc-9483-ecbeaec23f61   6.496402  ...  1.174342          2
306111  cf541822-5c5f-4f45-a602-3bdf4af04410   7.603153  ...  1.145947          2
50390   6dca73b7-d81e-4130-a429-ee6bbc174c2f   8.620224  ...  1.205134          2

[7386 rows x 6 

In [116]:
print(y_train)

250453        no stress
131662    time pressure
49100      interruption
10702     time pressure
121797        no stress
              ...      
117583     interruption
73349      interruption
312201        no stress
267336        no stress
128037     interruption
Name: condition, Length: 361903, dtype: object


In [117]:
print(y_test)

47340     time pressure
93858         no stress
201163     interruption
364634        no stress
54177         no stress
              ...      
260442    time pressure
254967        no stress
311243     interruption
306111        no stress
50390         no stress
Name: condition, Length: 7386, dtype: object


In [120]:


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn import preprocessing

x = df.iloc[:, 1:3].values
print ("\nOriginal data values : \n", x)


""" PART 4
	Handling the missing values """

from sklearn import preprocessing

""" MIN MAX SCALER """

min_max_scaler = preprocessing.MinMaxScaler(feature_range =(0, 1))

# Scaled feature
x_after_min_max_scaler = min_max_scaler.fit_transform(x)

print ("\nAfter min max Scaling : \n", x_after_min_max_scaler)


""" Standardisation """

Standardisation = preprocessing.StandardScaler()

# Scaled feature
x_after_Standardisation = Standardisation.fit_transform(x)

print ("\nAfter Standardisation : \n", x_after_Standardisation)



Original data values : 
 [[ 11.00156459 199.06178217]
 [  9.17012922 114.63445847]
 [ 11.53341728 118.93925348]
 ...
 [ 16.30453006 133.79779277]
 [ 11.83855289 110.31147414]
 [ 14.60630653  94.61780078]]

After min max Scaling : 
 [[0.47506419 0.21192414]
 [0.35235301 0.1006225 ]
 [0.51069977 0.10629757]
 ...
 [0.83037739 0.12588577]
 [0.53114469 0.09492345]
 [0.71659176 0.07423428]]

After Standardisation : 
 [[ 0.13992659  0.41112718]
 [-0.48839814 -0.36222874]
 [ 0.32239341 -0.32279673]
 ...
 [ 1.95925606 -0.18669222]
 [ 0.42707865 -0.40182736]
 [ 1.37663335 -0.54558171]]


In [121]:
print(x_test)

                                        uuid        SD1  ...    higuci  datasetId
47340   80ffbdb6-9cee-44b7-91b3-cf26ac25e5d5  10.235520  ...  1.162558          2
93858   eb61e4c8-c28f-4087-82b8-b427a5a52bef   7.750247  ...  1.157278          2
201163  80f5f9e2-a85d-4a51-8b89-39505b206ccf   8.678615  ...  1.184945          2
364634  c81a3c50-ee66-459a-9d55-a8261093c724  11.998805  ...  1.147558          2
54177   21eef6fc-3b7d-4ec7-a07e-202ca0075a4d  13.939728  ...  1.321684          2
...                                      ...        ...  ...       ...        ...
260442  d3e71cd1-5ed4-408d-9e06-72e013dc30bb   9.994420  ...  1.181154          2
254967  60491e54-94c5-4dce-ab6e-c3021db5b833   7.011343  ...  1.150296          2
311243  ae461c66-ec6c-4cfc-9483-ecbeaec23f61   6.496402  ...  1.174342          2
306111  cf541822-5c5f-4f45-a602-3bdf4af04410   7.603153  ...  1.145947          2
50390   6dca73b7-d81e-4130-a429-ee6bbc174c2f   8.620224  ...  1.205134          2

[7386 rows x 6 